# Venture Funding with Deep Learning

You work as a risk management associate at Alphabet Soup, a venture capital firm. Alphabet Soup’s business team receives many funding applications from startups every day. This team has asked you to help them create a model that predicts whether applicants will be successful if funded by Alphabet Soup.

The business team has given you a CSV containing more than 34,000 organizations that have received funding from Alphabet Soup over the years. With your knowledge of machine learning and neural networks, you decide to use the features in the provided dataset to create a binary classifier model that will predict whether an applicant will become a successful business. The CSV file contains a variety of information about these businesses, including whether or not they ultimately became successful.

## Instructions:

The steps for this challenge are broken out into the following sections:

* Prepare the data for use on a neural network model.

* Compile and evaluate a binary classification model using a neural network.

* Optimize the neural network model.

### Prepare the Data for Use on a Neural Network Model 

Using your knowledge of Pandas and scikit-learn’s `StandardScaler()`, preprocess the dataset so that you can use it to compile and evaluate the neural network model later.

Open the starter code file, and complete the following data preparation steps:

1. Read the `applicants_data.csv` file into a Pandas DataFrame. Review the DataFrame, looking for categorical variables that will need to be encoded, as well as columns that could eventually define your features and target variables.   

2. Drop the “EIN” (Employer Identification Number) and “NAME” columns from the DataFrame, because they are not relevant to the binary classification model.
 
3. Encode the dataset’s categorical variables using `OneHotEncoder`, and then place the encoded variables into a new DataFrame.

4. Add the original DataFrame’s numerical variables to the DataFrame containing the encoded variables.

> **Note** To complete this step, you will employ the Pandas `concat()` function that was introduced earlier in this course. 

5. Using the preprocessed data, create the features (`X`) and target (`y`) datasets. The target dataset should be defined by the preprocessed DataFrame column “IS_SUCCESSFUL”. The remaining columns should define the features dataset. 

6. Split the features and target sets into training and testing datasets.

7. Use scikit-learn's `StandardScaler` to scale the features data.

### Compile and Evaluate a Binary Classification Model Using a Neural Network

Use your knowledge of TensorFlow to design a binary classification deep neural network model. This model should use the dataset’s features to predict whether an Alphabet Soup&ndash;funded startup will be successful based on the features in the dataset. Consider the number of inputs before determining the number of layers that your model will contain or the number of neurons on each layer. Then, compile and fit your model. Finally, evaluate your binary classification model to calculate the model’s loss and accuracy. 
 
To do so, complete the following steps:

1. Create a deep neural network by assigning the number of input features, the number of layers, and the number of neurons on each layer using Tensorflow’s Keras.

> **Hint** You can start with a two-layer deep neural network model that uses the `relu` activation function for both layers.

2. Compile and fit the model using the `binary_crossentropy` loss function, the `adam` optimizer, and the `accuracy` evaluation metric.

> **Hint** When fitting the model, start with a small number of epochs, such as 20, 50, or 100.

3. Evaluate the model using the test data to determine the model’s loss and accuracy.

4. Save and export your model to an HDF5 file, and name the file `AlphabetSoup.h5`. 

### Optimize the Neural Network Model

Using your knowledge of TensorFlow and Keras, optimize your model to improve the model's accuracy. Even if you do not successfully achieve a better accuracy, you'll need to demonstrate at least two attempts to optimize the model. You can include these attempts in your existing notebook. Or, you can make copies of the starter notebook in the same folder, rename them, and code each model optimization in a new notebook. 

> **Note** You will not lose points if your model does not achieve a high accuracy, as long as you make at least two attempts to optimize the model.

To do so, complete the following steps:

1. Define at least three new deep neural network models (the original plus 2 optimization attempts). With each, try to improve on your first model’s predictive accuracy.

> **Rewind** Recall that perfect accuracy has a value of 1, so accuracy improves as its value moves closer to 1. To optimize your model for a predictive accuracy as close to 1 as possible, you can use any or all of the following techniques:
>
> * Adjust the input data by dropping different features columns to ensure that no variables or outliers confuse the model.
>
> * Add more neurons (nodes) to a hidden layer.
>
> * Add more hidden layers.
>
> * Use different activation functions for the hidden layers.
>
> * Add to or reduce the number of epochs in the training regimen.

2. After finishing your models, display the accuracy scores achieved by each model, and compare the results.

3. Save each of your models as an HDF5 file.

In [1]:
# Imports
import pandas as pd
from pathlib import Path
import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,OneHotEncoder

---

## Prepare the data to be used on a neural network model

### Step 1: Read the `applicants_data.csv` file into a Pandas DataFrame. Review the DataFrame, looking for categorical variables that will need to be encoded, as well as columns that could eventually define your features and target variables.

In [2]:
# Read the applicants_data.csv file from the Resources folder into a Pandas DataFrame
applicant_data_df = pd.read_csv(Path('Resources/applicants_data.csv'))

# Review the DataFrame
display(applicant_data_df.head())

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [3]:
# Review the data types associated with the columns
print(applicant_data_df.dtypes)

EIN                        int64
NAME                      object
APPLICATION_TYPE          object
AFFILIATION               object
CLASSIFICATION            object
USE_CASE                  object
ORGANIZATION              object
STATUS                     int64
INCOME_AMT                object
SPECIAL_CONSIDERATIONS    object
ASK_AMT                    int64
IS_SUCCESSFUL              int64
dtype: object

### Step 2: Drop the “EIN” (Employer Identification Number) and “NAME” columns from the DataFrame, because they are not relevant to the binary classification model.

In [4]:
# Drop the 'EIN' and 'NAME' columns from the DataFrame
applicant_data_df = applicant_data_df.drop(columns=['EIN','NAME'])

# Review the DataFrame
display(applicant_data_df.head())

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

### Step 3: Encode the dataset’s categorical variables using `OneHotEncoder`, and then place the encoded variables into a new DataFrame.

In [5]:
# Create a list of categorical variables 
categorical_variables = [
    'APPLICATION_TYPE',
    'AFFILIATION',
    'CLASSIFICATION',
    'USE_CASE',
    'ORGANIZATION',
    'INCOME_AMT',
    'SPECIAL_CONSIDERATIONS'
    ]

# Display the categorical variables list
print(categorical_variables)

['APPLICATION_TYPE', 'AFFILIATION', 'CLASSIFICATION', 'USE_CASE', 'ORGANIZATION', 'INCOME_AMT', 'SPECIAL_CONSIDERATIONS']

In [6]:
# Create a OneHotEncoder instance
enc = OneHotEncoder(sparse=False)

In [7]:
# Encode the categorcal variables using OneHotEncoder
encoded_data = enc.fit_transform(applicant_data_df[categorical_variables])

In [8]:
# Create a DataFrame with the encoded variables
encoded_df = pd.DataFrame(
    encoded_data,
    columns = enc.get_feature_names_out(categorical_variables)
)

# Review the DataFrame
display(encoded_df.head())

,APPLICATION_TYPE_T10,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T14,APPLICATION_TYPE_T15,APPLICATION_TYPE_T17,APPLICATION_TYPE_T19,APPLICATION_TYPE_T2,APPLICATION_TYPE_T25,APPLICATION_TYPE_T29,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

### Step 4: Add the original DataFrame’s numerical variables to the DataFrame containing the encoded variables.

> **Note** To complete this step, you will employ the Pandas `concat()` function that was introduced earlier in this course.

In [9]:
# Add the numerical variables from the original DataFrame to the one-hot encoding DataFrame
encoded_df = pd.concat(
    [
        applicant_data_df.drop(columns=categorical_variables), 
        encoded_df
    ], 
        axis=1
    )

# Review the Dataframe
display(encoded_df.head())

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_T10,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T14,APPLICATION_TYPE_T15,APPLICATION_TYPE_T17,APPLICATION_TYPE_T19,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,1,108590,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,1,5000,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,1,6692,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,1,142590,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

### Step 5: Using the preprocessed data, create the features (`X`) and target (`y`) datasets. The target dataset should be defined by the preprocessed DataFrame column “IS_SUCCESSFUL”. The remaining columns should define the features dataset.

In [10]:
# Define the target set y using the IS_SUCCESSFUL column
y = encoded_df['IS_SUCCESSFUL']

# Display a sample of y
y[-5:]

34294    0
34295    0
34296    0
34297    1
34298    0
Name: IS_SUCCESSFUL, dtype: int64

In [11]:
# Define features set X by selecting all columns but IS_SUCCESSFUL
X = encoded_df.drop(columns=['IS_SUCCESSFUL'])

# Review the features DataFrame
display(X.head())

,STATUS,ASK_AMT,APPLICATION_TYPE_T10,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T14,APPLICATION_TYPE_T15,APPLICATION_TYPE_T17,APPLICATION_TYPE_T19,APPLICATION_TYPE_T2,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,1,108590,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,1,5000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,1,6692,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,1,142590,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

### Step 6: Split the features and target sets into training and testing datasets.

In [12]:
# Split the preprocessed data into a training and testing dataset
# Assign the function a random_state equal to 1
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

### Step 7: Use scikit-learn's `StandardScaler` to scale the features data.

In [13]:
# Create a StandardScaler instance
scaler = StandardScaler()

# Fit the scaler to the features training dataset
X_scaler = scaler.fit(X_train)

# Fit the scaler to the features training dataset
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

---

## Compile and Evaluate a Binary Classification Model Using a Neural Network

### Step 1: Create a deep neural network by assigning the number of input features, the number of layers, and the number of neurons on each layer using Tensorflow’s Keras.

> **Hint** You can start with a two-layer deep neural network model that uses the `relu` activation function for both layers.

In [14]:
# Define the the number of inputs (features) to the model
number_input_features = len(X_train.iloc[0])

# Review the number of features
number_input_features

116

In [15]:
# Define the number of neurons in the output layer
number_output_neurons = 1

In [16]:
# Define the number of hidden nodes for the first hidden layer
hidden_nodes_layer1 =  (number_input_features + 1) // 2 

# Review the number hidden nodes in the first layer
hidden_nodes_layer1

58

In [17]:
# Define the number of hidden nodes for the second hidden layer
hidden_nodes_layer2 =  (hidden_nodes_layer1 + 1) // 2

# Review the number hidden nodes in the second layer
hidden_nodes_layer2

29

In [18]:
# Create the Sequential model instance
nn = Sequential()

2022-07-02 17:36:09.046883: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.

In [19]:
# Add the first hidden layer
nn.add(Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation='relu'))

In [20]:
# Add the second hidden layer
nn.add(Dense(units=hidden_nodes_layer2, activation='relu'))

In [21]:
# Add the output layer to the model specifying the number of output neurons and activation function
nn.add(Dense(units=number_output_neurons, activation='relu'))

In [22]:
# Display the Sequential model summary
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 58)                6786

 dense_1 (Dense)             (None, 29)                1711

 dense_2 (Dense)             (None, 1)                 30

=================================================================
Total params: 8,527
Trainable params: 8,527
Non-trainable params: 0
_________________________________________________________________

### Step 2: Compile and fit the model using the `binary_crossentropy` loss function, the `adam` optimizer, and the `accuracy` evaluation metric.

In [23]:
# Compile the Sequential model
nn.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [24]:
# Fit the model using 50 epochs and the training data
fit_model = nn.fit(X_train_scaled, y_train, epochs=50)

Epoch 1/50
804/804 [==============================] - 1s 1ms/step - loss: 1.1836 - accuracy: 0.6821
Epoch 2/50
804/804 [==============================] - 1s 1ms/step - loss: 1.2197 - accuracy: 0.6944
Epoch 3/50
804/804 [==============================] - 1s 1ms/step - loss: 0.9072 - accuracy: 0.7169
Epoch 4/50
804/804 [==============================] - 1s 1ms/step - loss: 0.8711 - accuracy: 0.7202
Epoch 5/50
804/804 [==============================] - 1s 1ms/step - loss: 0.8518 - accuracy: 0.7236
Epoch 6/50
804/804 [==============================] - 1s 1ms/step - loss: 0.8990 - accuracy: 0.7144
Epoch 7/50
804/804 [==============================] - 1s 1ms/step - loss: 0.8852 - accuracy: 0.7123
Epoch 8/50
804/804 [==============================] - 1s 1ms/step - loss: 0.8339 - accuracy: 0.7219
Epoch 9/50
804/804 [==============================] - 1s 1ms/step - loss: 0.8658 - accuracy: 0.7169
Epoch 10/50
804/804 [==============================] - 1s 1ms/step - loss: 0.9495 - accuracy: 0.6981
Epoch 11/50
804/804 [==============================] - 1s 1ms/step - loss: 0.8551 - accuracy: 0.7114
Epoch 12/50
804/804 [==============================] - 1s 1ms/step - loss: 0.8562 - accuracy: 0.7119
Epoch 13/50
804/804 [==============================] - 1s 1ms/step - loss: 0.8354 - accuracy: 0.7130
Epoch 14/50
804/804 [==============================] - 1s 1ms/step - loss: 0.7476 - accuracy: 0.7270
Epoch 15/50
804/804 [==============================] - 1s 1ms/step - loss: 0.7519 - accuracy: 0.7223
Epoch 16/50
804/804 [==============================] - 1s 1ms/step - loss: 0.7160 - accuracy: 0.7265
Epoch 17/50
804/804 [==============================] - 1s 1ms/step - loss: 0.7284 - accuracy: 0.7287
Epoch 18/50
804/804 [==============================] - 1s 1ms/step - loss: 0.7313 - accuracy: 0.7234
Epoch 19/50
804/804 [==============================] - 1s 1ms/step - loss: 0.6845 - accuracy: 0.7247
Epoch 20/50
804/804 [==============================] - 1s 1ms/step - loss: 0.7404 - accuracy: 0.7217
Epoch 21/50
804/804 [==============================] - 1s 1ms/step - loss: 0.6861 - accuracy: 0.7248
Epoch 22/50
804/804 [==============================] - 1s 2ms/step - loss: 0.6870 - accuracy: 0.7306
Epoch 23/50
804/804 [==============================] - 2s 2ms/step - loss: 0.6816 - accuracy: 0.7320
Epoch 24/50
804/804 [==============================] - 2s 2ms/step - loss: 0.6858 - accuracy: 0.7288
Epoch 25/50
804/804 [==============================] - 1s 1ms/step - loss: 0.6780 - accuracy: 0.7237
Epoch 26/50
804/804 [==============================] - 1s 1ms/step - loss: 0.6807 - accuracy: 0.7290
Epoch 27/50
804/804 [==============================] - 1s 1ms/step - loss: 0.7152 - accuracy: 0.7263
Epoch 28/50
804/804 [==============================] - 1s 1ms/step - loss: 0.6751 - accuracy: 0.7310
Epoch 29/50
804/804 [==============================] - 1s 1ms/step - loss: 0.6825 - accuracy: 0.7324
Epoch 30/50
804/804 [==============================] - 1s 1ms/step - loss: 0.6859 - accuracy: 0.7324
Epoch 31/50
804/804 [==============================] - 1s 1ms/step - loss: 0.6873 - accuracy: 0.7316
Epoch 32/50
804/804 [==============================] - 1s 1ms/step - loss: 0.6830 - accuracy: 0.7328
Epoch 33/50
804/804 [==============================] - 1s 2ms/step - loss: 0.6788 - accuracy: 0.7319
Epoch 34/50
804/804 [==============================] - 1s 1ms/step - loss: 0.6708 - accuracy: 0.7284
Epoch 35/50
804/804 [==============================] - 1s 1ms/step - loss: 0.6748 - accuracy: 0.7308
Epoch 36/50
804/804 [==============================] - 1s 1ms/step - loss: 0.6536 - accuracy: 0.7331
Epoch 37/50
804/804 [==============================] - 1s 1ms/step - loss: 0.6668 - accuracy: 0.7325
Epoch 38/50
804/804 [==============================] - 1s 1ms/step - loss: 0.6587 - accuracy: 0.7339
Epoch 39/50
804/804 [==============================] - 1s 2ms/step - loss: 0.6679 - accuracy: 0.7291
Epoch 40/50
804/804 [==============================] - 1s 1ms/step - loss: 0.6568 - accuracy: 0.7320
Epoch 41/50
804/804 [==============================] - 1s 1ms/step - loss: 0.6730 - accuracy: 0.7290
Epoch 42/50
804/804 [==============================] - 1s 1ms/step - loss: 0.6599 - accuracy: 0.7337
Epoch 43/50
804/804 [==============================] - 1s 1ms/step - loss: 0.6488 - accuracy: 0.7330
Epoch 44/50
804/804 [==============================] - 1s 1ms/step - loss: 0.6266 - accuracy: 0.7337
Epoch 45/50
804/804 [==============================] - 1s 1ms/step - loss: 0.6282 - accuracy: 0.7346
Epoch 46/50
804/804 [==============================] - 1s 2ms/step - loss: 0.6390 - accuracy: 0.7295
Epoch 47/50
804/804 [==============================] - 2s 2ms/step - loss: 0.6303 - accuracy: 0.7343
Epoch 48/50
804/804 [==============================] - 1s 1ms/step - loss: 0.6214 - accuracy: 0.7341
Epoch 49/50
804/804 [==============================] - 1s 1ms/step - loss: 0.6435 - accuracy: 0.7266
Epoch 50/50
804/804 [==============================] - 1s 1ms/step - loss: 0.6395 - accuracy: 0.7303

### Step 3: Evaluate the model using the test data to determine the model’s loss and accuracy.

In [25]:
# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled, y_test)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 [==============================] - 0s 949us/step - loss: 0.6240 - accuracy: 0.7306
Loss: 0.6240286827087402, Accuracy: 0.7306122183799744

### Step 4: Save and export your model to an HDF5 file, and name the file `AlphabetSoup.h5`.

In [26]:
# Set the model's file path
file_path = Path('Models/AlphabetSoup.h5')

# Export your model to a HDF5 file
nn.save(file_path)

---

## Optimize the neural network model

### Step 1: Define at least three new deep neural network models (resulting in the original plus 3 optimization attempts). With each, try to improve on your first model’s predictive accuracy.

> **Rewind** Recall that perfect accuracy has a value of 1, so accuracy improves as its value moves closer to 1. To optimize your model for a predictive accuracy as close to 1 as possible, you can use any or all of the following techniques:
>
> * Adjust the input data by dropping different features columns to ensure that no variables or outliers confuse the model.
>
> * Add more neurons (nodes) to a hidden layer.
>
> * Add more hidden layers.
>
> * Use different activation functions for the hidden layers.
>
> * Add to or reduce the number of epochs in the training regimen.

### Alternative Model 1

In [27]:
# Define the the number of inputs (features) to the model
number_input_features = len(X_train.iloc[0])

# Review the number of features
number_input_features

116

In [28]:
# Define the number of neurons in the output layer
number_output_neurons_A1 = 1

In [29]:
# Define the number of hidden nodes for the first hidden layer
hidden_nodes_layer1_A1 = (number_input_features + 1) // 2

# Review the number of hidden nodes in the first layer
hidden_nodes_layer1_A1

58

In [30]:
# Create the Sequential model instance
nn_A1 = Sequential()

In [31]:
# First hidden layer
nn_A1.add(Dense(units=hidden_nodes_layer1_A1, input_dim=number_input_features, activation='relu'))

# Output layer
nn.add(Dense(units=number_output_neurons_A1, activation='relu'))

# Check the structure of the model
nn_A1.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_3 (Dense)             (None, 58)                6786

=================================================================
Total params: 6,786
Trainable params: 6,786
Non-trainable params: 0
_________________________________________________________________

In [32]:
# Compile the Sequential model
nn_A1.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [33]:
# Fit the model using 50 epochs and the training data
fit_model_A1 = nn_A1.fit(X_train_scaled, y_train, epochs=75)

Epoch 1/75
804/804 [==============================] - 1s 1ms/step - loss: 3.3437 - accuracy: 0.0022
Epoch 2/75
804/804 [==============================] - 1s 1ms/step - loss: 2.5098 - accuracy: 0.0034
Epoch 3/75
804/804 [==============================] - 1s 1ms/step - loss: 2.2600 - accuracy: 0.0086
Epoch 4/75
804/804 [==============================] - 1s 1ms/step - loss: 2.0483 - accuracy: 0.0144
Epoch 5/75
804/804 [==============================] - 1s 1ms/step - loss: 1.9500 - accuracy: 0.0034
Epoch 6/75
804/804 [==============================] - 1s 1ms/step - loss: 1.8843 - accuracy: 0.0036
Epoch 7/75
804/804 [==============================] - 1s 1ms/step - loss: 1.8344 - accuracy: 0.0097
Epoch 8/75
804/804 [==============================] - 1s 1ms/step - loss: 1.7927 - accuracy: 0.0100
Epoch 9/75
804/804 [==============================] - 1s 1ms/step - loss: 1.7587 - accuracy: 0.0050
Epoch 10/75
804/804 [==============================] - 1s 1ms/step - loss: 1.7196 - accuracy: 0.0105
Epoch 11/75
804/804 [==============================] - 1s 1ms/step - loss: 1.6991 - accuracy: 0.0135
Epoch 12/75
804/804 [==============================] - 1s 1ms/step - loss: 1.6966 - accuracy: 0.0109
Epoch 13/75
804/804 [==============================] - 1s 1ms/step - loss: 1.6800 - accuracy: 0.0196
Epoch 14/75
804/804 [==============================] - 1s 1ms/step - loss: 1.6761 - accuracy: 0.0263
Epoch 15/75
804/804 [==============================] - 1s 1ms/step - loss: 1.6664 - accuracy: 0.0328
Epoch 16/75
804/804 [==============================] - 1s 1ms/step - loss: 1.6491 - accuracy: 0.0267
Epoch 17/75
804/804 [==============================] - 1s 1ms/step - loss: 1.6434 - accuracy: 0.0225
Epoch 18/75
804/804 [==============================] - 1s 1ms/step - loss: 1.6394 - accuracy: 0.0149
Epoch 19/75
804/804 [==============================] - 1s 1ms/step - loss: 1.6319 - accuracy: 0.0175
Epoch 20/75
804/804 [==============================] - 1s 1ms/step - loss: 1.6287 - accuracy: 0.0381
Epoch 21/75
804/804 [==============================] - 1s 1ms/step - loss: 1.6249 - accuracy: 0.2505
Epoch 22/75
804/804 [==============================] - 1s 1ms/step - loss: 1.6227 - accuracy: 0.2247
Epoch 23/75
804/804 [==============================] - 1s 1ms/step - loss: 1.6250 - accuracy: 0.1458
Epoch 24/75
804/804 [==============================] - 1s 1ms/step - loss: 1.6155 - accuracy: 0.0217
Epoch 25/75
804/804 [==============================] - 1s 1ms/step - loss: 1.6100 - accuracy: 0.0230
Epoch 26/75
804/804 [==============================] - 1s 1ms/step - loss: 1.6122 - accuracy: 0.0168
Epoch 27/75
804/804 [==============================] - 1s 1ms/step - loss: 1.6073 - accuracy: 0.0154
Epoch 28/75
804/804 [==============================] - 1s 1ms/step - loss: 1.6025 - accuracy: 0.0202
Epoch 29/75
804/804 [==============================] - 1s 1ms/step - loss: 1.6019 - accuracy: 0.0159
Epoch 30/75
804/804 [==============================] - 1s 1ms/step - loss: 1.6002 - accuracy: 0.0173
Epoch 31/75
804/804 [==============================] - 1s 1ms/step - loss: 1.5967 - accuracy: 0.0239
Epoch 32/75
804/804 [==============================] - 1s 1ms/step - loss: 1.5945 - accuracy: 0.0209
Epoch 33/75
804/804 [==============================] - 1s 1ms/step - loss: 1.5995 - accuracy: 0.0152
Epoch 34/75
804/804 [==============================] - 1s 1ms/step - loss: 1.5955 - accuracy: 0.0227
Epoch 35/75
804/804 [==============================] - 1s 1ms/step - loss: 1.5900 - accuracy: 0.0168
Epoch 36/75
804/804 [==============================] - 1s 1ms/step - loss: 1.5765 - accuracy: 0.0135
Epoch 37/75
804/804 [==============================] - 1s 1ms/step - loss: 1.5770 - accuracy: 0.0168
Epoch 38/75
804/804 [==============================] - 1s 1ms/step - loss: 1.5728 - accuracy: 0.0170
Epoch 39/75
804/804 [==============================] - 1s 1ms/step - loss: 1.5733 - accuracy: 0.0154
Epoch 40/75
804/804 [==============================] - 1s 1ms/step - loss: 1.5746 - accuracy: 0.0164
Epoch 41/75
804/804 [==============================] - 1s 1ms/step - loss: 1.5701 - accuracy: 0.0245
Epoch 42/75
804/804 [==============================] - 1s 1ms/step - loss: 1.5683 - accuracy: 0.0344
Epoch 43/75
804/804 [==============================] - 1s 1ms/step - loss: 1.5753 - accuracy: 0.0412
Epoch 44/75
804/804 [==============================] - 1s 1ms/step - loss: 1.5709 - accuracy: 0.0247
Epoch 45/75
804/804 [==============================] - 1s 1ms/step - loss: 1.5740 - accuracy: 0.0141
Epoch 46/75
804/804 [==============================] - 1s 1ms/step - loss: 1.5649 - accuracy: 0.0149
Epoch 47/75
804/804 [==============================] - 1s 1ms/step - loss: 1.5660 - accuracy: 0.0219
Epoch 48/75
804/804 [==============================] - 1s 1ms/step - loss: 1.5643 - accuracy: 0.0221
Epoch 49/75
804/804 [==============================] - 1s 1ms/step - loss: 1.5688 - accuracy: 0.0137
Epoch 50/75
804/804 [==============================] - 1s 1ms/step - loss: 1.5665 - accuracy: 0.0558
Epoch 51/75
804/804 [==============================] - 1s 1ms/step - loss: 1.5629 - accuracy: 0.0271
Epoch 52/75
804/804 [==============================] - 1s 1ms/step - loss: 1.5633 - accuracy: 0.0252
Epoch 53/75
804/804 [==============================] - 1s 1ms/step - loss: 1.5648 - accuracy: 0.0386
Epoch 54/75
804/804 [==============================] - 1s 1ms/step - loss: 1.5703 - accuracy: 0.0141
Epoch 55/75
804/804 [==============================] - 1s 1ms/step - loss: 1.5647 - accuracy: 0.0134
Epoch 56/75
804/804 [==============================] - 1s 1ms/step - loss: 1.5635 - accuracy: 0.0152
Epoch 57/75
804/804 [==============================] - 1s 1ms/step - loss: 1.5664 - accuracy: 0.0146
Epoch 58/75
804/804 [==============================] - 1s 1ms/step - loss: 1.5641 - accuracy: 0.0210
Epoch 59/75
804/804 [==============================] - 1s 1ms/step - loss: 1.5648 - accuracy: 0.0208
Epoch 60/75
804/804 [==============================] - 1s 1ms/step - loss: 1.5661 - accuracy: 0.0229
Epoch 61/75
804/804 [==============================] - 1s 1ms/step - loss: 1.5648 - accuracy: 0.0297
Epoch 62/75
804/804 [==============================] - 1s 1ms/step - loss: 1.5679 - accuracy: 0.0166
Epoch 63/75
804/804 [==============================] - 1s 1ms/step - loss: 1.5644 - accuracy: 0.0140
Epoch 64/75
804/804 [==============================] - 1s 1ms/step - loss: 1.5660 - accuracy: 0.0157
Epoch 65/75
804/804 [==============================] - 1s 1ms/step - loss: 1.5641 - accuracy: 0.0529
Epoch 66/75
804/804 [==============================] - 1s 1ms/step - loss: 1.5630 - accuracy: 0.0529
Epoch 67/75
804/804 [==============================] - 1s 1ms/step - loss: 1.5649 - accuracy: 0.0442
Epoch 68/75
804/804 [==============================] - 1s 1ms/step - loss: 1.5658 - accuracy: 0.0269
Epoch 69/75
804/804 [==============================] - 1s 1ms/step - loss: 1.5640 - accuracy: 0.0136
Epoch 70/75
804/804 [==============================] - 1s 1ms/step - loss: 1.5615 - accuracy: 0.0194
Epoch 71/75
804/804 [==============================] - 1s 1ms/step - loss: 1.5633 - accuracy: 0.0178
Epoch 72/75
804/804 [==============================] - 1s 1ms/step - loss: 1.5693 - accuracy: 0.0266
Epoch 73/75
804/804 [==============================] - 1s 1ms/step - loss: 1.5634 - accuracy: 0.0225
Epoch 74/75
804/804 [==============================] - 1s 1ms/step - loss: 1.5672 - accuracy: 0.0140
Epoch 75/75
804/804 [==============================] - 1s 1ms/step - loss: 1.5659 - accuracy: 0.0143

#### Alternative Model 2

In [34]:
# Define the the number of inputs (features) to the model
number_input_features = len(X_train.iloc[0])

# Review the number of features
number_input_features

116

In [35]:
# Define the number of neurons in the output layer
number_output_neurons_A2 = 1

In [36]:
# Define the number of hidden nodes for the first hidden layer
hidden_nodes_layer1_A2 = (number_input_features + 1) // 2

# Review the number of hidden nodes in the first layer
hidden_nodes_layer1_A2

58

In [37]:
# Create the Sequential model instance
nn_A2 = Sequential()

In [38]:
# First hidden layer
nn_A2.add(Dense(units=hidden_nodes_layer1_A2, input_dim=number_input_features, activation='relu'))

# Output layer
nn_A2.add(Dense(units=number_output_neurons_A2, activation='relu'))

# Check the structure of the model
nn_A2.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_5 (Dense)             (None, 58)                6786

 dense_6 (Dense)             (None, 1)                 59

=================================================================
Total params: 6,845
Trainable params: 6,845
Non-trainable params: 0
_________________________________________________________________

In [39]:
# Compile the model
nn_A2.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [40]:
# Fit the model
fit_model_A2 = nn_A2.fit(X_train_scaled, y_train, epochs=50)

Epoch 1/50
804/804 [==============================] - 1s 1ms/step - loss: 1.1932 - accuracy: 0.6821
Epoch 2/50
804/804 [==============================] - 1s 1ms/step - loss: 1.1434 - accuracy: 0.6987
Epoch 3/50
804/804 [==============================] - 1s 1ms/step - loss: 1.3625 - accuracy: 0.6839
Epoch 4/50
804/804 [==============================] - 1s 1ms/step - loss: 1.5560 - accuracy: 0.6892
Epoch 5/50
804/804 [==============================] - 1s 1ms/step - loss: 1.6613 - accuracy: 0.6794
Epoch 6/50
804/804 [==============================] - 1s 1ms/step - loss: 1.4520 - accuracy: 0.6810
Epoch 7/50
804/804 [==============================] - 1s 1ms/step - loss: 1.5452 - accuracy: 0.6843
Epoch 8/50
804/804 [==============================] - 1s 1ms/step - loss: 1.2867 - accuracy: 0.7077
Epoch 9/50
804/804 [==============================] - 1s 1ms/step - loss: 1.3643 - accuracy: 0.7040
Epoch 10/50
804/804 [==============================] - 1s 1ms/step - loss: 1.4169 - accuracy: 0.6977
Epoch 11/50
804/804 [==============================] - 1s 1ms/step - loss: 1.4104 - accuracy: 0.6972
Epoch 12/50
804/804 [==============================] - 1s 1ms/step - loss: 1.3609 - accuracy: 0.6860
Epoch 13/50
804/804 [==============================] - 1s 1ms/step - loss: 1.2519 - accuracy: 0.6960
Epoch 14/50
804/804 [==============================] - 2s 2ms/step - loss: 1.1923 - accuracy: 0.7001
Epoch 15/50
804/804 [==============================] - 1s 1ms/step - loss: 1.2485 - accuracy: 0.7018
Epoch 16/50
804/804 [==============================] - 1s 1ms/step - loss: 1.1903 - accuracy: 0.7117
Epoch 17/50
804/804 [==============================] - 1s 1ms/step - loss: 0.9160 - accuracy: 0.7151
Epoch 18/50
804/804 [==============================] - 1s 1ms/step - loss: 0.8772 - accuracy: 0.7247
Epoch 19/50
804/804 [==============================] - 1s 1ms/step - loss: 0.8801 - accuracy: 0.7203
Epoch 20/50
804/804 [==============================] - 1s 1ms/step - loss: 0.9127 - accuracy: 0.7153
Epoch 21/50
804/804 [==============================] - 1s 1ms/step - loss: 0.9248 - accuracy: 0.7136
Epoch 22/50
804/804 [==============================] - 1s 1ms/step - loss: 0.9092 - accuracy: 0.7198
Epoch 23/50
804/804 [==============================] - 1s 1ms/step - loss: 0.9312 - accuracy: 0.7209
Epoch 24/50
804/804 [==============================] - 1s 1ms/step - loss: 0.9581 - accuracy: 0.7086
Epoch 25/50
804/804 [==============================] - 1s 1ms/step - loss: 1.0758 - accuracy: 0.7099
Epoch 26/50
804/804 [==============================] - 1s 2ms/step - loss: 0.9664 - accuracy: 0.7170
Epoch 27/50
804/804 [==============================] - 1s 1ms/step - loss: 1.0074 - accuracy: 0.7162
Epoch 28/50
804/804 [==============================] - 1s 2ms/step - loss: 1.0366 - accuracy: 0.7119
Epoch 29/50
804/804 [==============================] - 1s 1ms/step - loss: 0.9887 - accuracy: 0.7151
Epoch 30/50
804/804 [==============================] - 1s 1ms/step - loss: 0.9040 - accuracy: 0.7177
Epoch 31/50
804/804 [==============================] - 1s 1ms/step - loss: 0.9018 - accuracy: 0.7190
Epoch 32/50
804/804 [==============================] - 1s 1ms/step - loss: 0.8952 - accuracy: 0.7207
Epoch 33/50
804/804 [==============================] - 1s 1ms/step - loss: 0.8901 - accuracy: 0.7147
Epoch 34/50
804/804 [==============================] - 1s 1ms/step - loss: 0.8815 - accuracy: 0.7156
Epoch 35/50
804/804 [==============================] - 1s 1ms/step - loss: 0.8973 - accuracy: 0.6990
Epoch 36/50
804/804 [==============================] - 1s 1ms/step - loss: 0.7972 - accuracy: 0.7176
Epoch 37/50
804/804 [==============================] - 1s 1ms/step - loss: 0.7323 - accuracy: 0.7271
Epoch 38/50
804/804 [==============================] - 1s 2ms/step - loss: 0.7081 - accuracy: 0.7308
Epoch 39/50
804/804 [==============================] - 1s 1ms/step - loss: 0.7470 - accuracy: 0.7191
Epoch 40/50
804/804 [==============================] - 1s 1ms/step - loss: 0.7538 - accuracy: 0.7225
Epoch 41/50
804/804 [==============================] - 1s 1ms/step - loss: 0.7435 - accuracy: 0.7159
Epoch 42/50
804/804 [==============================] - 1s 1ms/step - loss: 0.7116 - accuracy: 0.7296
Epoch 43/50
804/804 [==============================] - 1s 1ms/step - loss: 0.7465 - accuracy: 0.7277
Epoch 44/50
804/804 [==============================] - 1s 1ms/step - loss: 0.7567 - accuracy: 0.7271
Epoch 45/50
804/804 [==============================] - 1s 1ms/step - loss: 0.7587 - accuracy: 0.7264
Epoch 46/50
804/804 [==============================] - 1s 1ms/step - loss: 0.7553 - accuracy: 0.7271
Epoch 47/50
804/804 [==============================] - 1s 1ms/step - loss: 0.7811 - accuracy: 0.7220
Epoch 48/50
804/804 [==============================] - 1s 1ms/step - loss: 0.7057 - accuracy: 0.7303
Epoch 49/50
804/804 [==============================] - 1s 1ms/step - loss: 0.6988 - accuracy: 0.7287
Epoch 50/50
804/804 [==============================] - 1s 1ms/step - loss: 0.7276 - accuracy: 0.7239

### Step 2: After finishing your models, display the accuracy scores achieved by each model, and compare the results.

In [41]:
print("Original Model Results")

# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled, y_test)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Original Model Results
268/268 [==============================] - 0s 1ms/step - loss: 0.6240 - accuracy: 0.7306
Loss: 0.6240286827087402, Accuracy: 0.7306122183799744

In [42]:
print("Alternative Model 1 Results")

# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn_A1.evaluate(X_test_scaled, y_test)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Alternative Model 1 Results
268/268 [==============================] - 0s 957us/step - loss: 1.5125 - accuracy: 0.0131
Loss: 1.51251220703125, Accuracy: 0.013061224482953548

In [43]:
print("Alternative Model 2 Results")

# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn_A2.evaluate(X_test_scaled, y_test)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Alternative Model 2 Results
268/268 [==============================] - 0s 978us/step - loss: 0.8002 - accuracy: 0.7159
Loss: 0.800159215927124, Accuracy: 0.7159183621406555

### Step 3: Save each of your alternative models as an HDF5 file.

In [44]:
# Set the file path for the first alternative model
file_path = Path('Models/AlphabetSoup_A1.h5')

# Export your model to a HDF5 file
nn_A1.save(file_path)

In [45]:
# Set the file path for the second alternative model
file_path = Path('Models/AlphabetSoup_A2.h5')

# Export your model to a HDF5 file
nn_A2.save(file_path)